### ISSUE TITLE
LA SCUOLA INFESTATA - GRAFICA

### ISSUE THREAD

**Issue by redtyyt** [redtyyt/La-Scuola-Infestata#3]
`!Fase di sviluppo Alpha!`
### Disegnare IMMAGINI, WALLPAPER...

> @ByLupo345, @eCampi1, @Alessiox13, @Gabrielltommy, @RonyxDumb 

```
Importante
```

**Comment by redtyyt** [comment]
![IMG-20230317-WA0008.jpg](https://user-images.githubusercontent.com/111154398/225967191-91d06013-ef7b-4e9f-ac8a-eb711b0d2366.jpg)

**Comment by redtyyt** [comment]
![IMG-20230317-WA0015.jpg](https://user-im![IMG-20230317-WA0014.jpg](https://user-images.githubusercontent.com/111154398/226045446-234f58d6-cdad-42e2-ac71-9c3c25da4190.jpg)

5404-3abc6a5c-d32d-4ee9-9048-0ef9b696d451.jpg)

![Uploading IMG-20230317-WA0014.jpg …]()

![IMG-20230317-WA0013.jpg](https://user-images.githubusercontent.com/111154398/226045534-408cb4ee-6816-463d-ac8d-657487b8fc55.jpg)

**Comment by redtyyt** [comment]
![IMG-20230317-WA0015.jpg](https://user-images.githubusercontent.com/111154398/226046251-2238bfd1-e96a-4808-8dd5-51348d65eb4d.jpg)

**Comment by redtyyt** [comment]
![IMG-20230317-WA0019.jpg](https://user-images.githubusercontent.com/111154398/226046554-2fbd3b47-e7b2-433b-bc78-b3bac57006b3.jpg)

**Comment by ByLupo345** [comment]
Ciao si lo visto il sito poi lo vediamo di nuovo

💕💕💕

Il ven 17 mar 2023, 22:01 redtyyt ***@***.***> ha scritto:

**Comment by redtyyt** [comment]
![IMG-20230318-WA0000.jpg](https://user-images.githubusercontent.com/111154398/226140475-8321be0e-d194-4c66-807b-7c786b296447.jpg)

**Comment by ByLupo345** [comment]
Ciao lo giusto
?

Il sab 18 mar 2023, 22:14 redtyyt ***@***.***> ha scritto:

**Comment by RonyxDumb** [comment]
Hey salve a tutti,
sono un conoscente di Alessiox13 di cui mi ha parlato di questo progetto, e ho visitato anche il sito per maggiori informazioni.
Ho letto che necessitate un pò d'aiuto, e pensavo che potessi contribuire nel mio piccolo per aiutarvi.
Quindi per cominciare, ho realizzato un prototipo di cosa sarà il menù per il Login (sinceramente non so che API usi, ma penso che richieda Username e Api), ma ho voluto mostrare cosa riesco a fare potenzialmente.

(PS oltre ad essere un Designer, sono un Semi-Programmatore che lavora con HaxeFlixel (Haxe, ".hx"), come si può notare dalla mia pagina Github)
 
![lsi_mpm_ConnectPrototype](https://user-images.githubusercontent.com/104029827/226204693-338c2450-fbc0-4169-a7cb-1278d8c4cb6d.png)

Inoltre leggendo il file README.txt ho visto che badate molto a leggi relative alla Licensa e l'uso dei Contenuti, e posso consigliarvi:
- Se volete una Licensa che afferma l'autorizzazione ai giocatori di Moddare il gioco (Come Friday Night Funkin'), ma che comunque vengono rispettati i vari crediti del team, usate la Licensa Apache 2.0

**Comment by ByLupo345** [comment]
![2e4f3e7b-2dad-420e-b15f-5232e6518409.png](https://user-images.githubusercontent.com/127892632/227360062-490bff54-2502-485b-b480-2b21ed272a9f.png)

**Comment by ByLupo345** [comment]
![2e4f3e7b-2dad-420e-b15f-5232e6518409.png](https://user-images.githubusercontent.com/127892632/227360062-490bff54-2502-485b-b480-2b21ed272a9f.png)

**Comment by ByLupo345** [comment]
![2e4f3e7b-2dad-420e-b15f-5232e6518409.png](https://user-images.githubusercontent.com/127892632/227361868-0a029556-950b-4e49-b9d5-5db6968b814e.png)

**Comment by ByLupo345** [comment]
![c6e2d6a4-bd49-4b3f-a6b5-2fcb85993924.png](https://user-images.githubusercontent.com/127892632/228048723-97969bb7-b0ba-4d46-99e0-925cc983725d.png)

Ecco fatto!

**Comment by ByLupo345** [comment]
va bene?

**Comment by ByLupo345** [comment]
fatto ti piace?

**Comment by ByLupo345** [comment]
![55ad664a-5f31-4c3d-bec8-9682ed528e09.png](https://user-images.githubusercontent.com/127892632/228345538-0ab056b5-c0b2-47a6-8556-c361ed80decf.png)

**Comment by ByLupo345** [comment]
Ti piace?

**Comment by ByLupo345** [comment]
![bb8d88a0-7d10-47c7-bace-e004adff87a0.png](https://user-images.githubusercontent.com/127892632/228643651-11bc245a-b0af-4231-85dc-abe64e9bcbd4.png)

**Comment by ByLupo345** [comment]
70db98eb-ab08-49f6-b68f-87afa82000d2.png -->

**Comment by Sdatyyt** [comment]
![Screenshot_20230410_101905.jpg](https://user-images.githubusercontent.com/130348653/230860635-832c5f60-586f-4ddc-92e2-39598f8324bf.jpg)

**Comment by Sdatyyt** [comment]
![Screenshot_20230410_102230.jpg](https://user-images.githubusercontent.com/130348653/230861653-36fbe7a0-6997-4c3d-a0f0-8125b3dbbf25.jpg)

**Comment by ByLupo345** [comment]
![09523988-fd45-4b49-904c-11138d69940c.png](https://user-images.githubusercontent.com/127892632/233805779-8b21e85d-00ff-40da-b9e1-b11719206953.png)

**Comment by ByLupo345** [comment]
https://user-images.githubusercontent.com/127892632/235321918-4abeb2b6-7c14-49f1-b904-2596267cc5d3.mp4

**Comment by ByLupo345** [comment]
12229368c8f8e30a57ff3e08c763d4212738cd94.pnj -->

**Comment by ByLupo345** [comment]
![backupPreview.png](https://user-images.githubusercontent.com/127892632/236033254-9906371e-49b3-48af-a4f8-be501e086f1f.png)

**Comment by ByLupo345** [comment]
![46ad5af3-2bc5-42ce-a9d2-ad4631f4740b.png](https://user-images.githubusercontent.com/127892632/236645312-af0d534d-bcb2-4f0b-b3f3-cb84a6d6634b.png)

**Comment by ByLupo345** [comment]
![219546f8-cdfb-446b-ac50-6b5c7a7d31d9.png](https://user-images.githubusercontent.com/127892632/236645343-49191b5e-66af-4370-b577-215e0c729ad5.png)

**Comment by ByLupo345** [comment]
![f4d004c1-c48b-4ffa-b495-1027c918b6f8.png](https://user-images.githubusercontent.com/127892632/236645467-f66295b2-aa62-48cf-b426-37f3f13afe3c.png)

**Comment by ByLupo345** [comment]
![f4d004c1-c48b-4ffa-b495-1027c918b6f8.png](https://user-images.githubusercontent.com/127892632/236645467-f66295b2-aa62-48cf-b426-37f3f13afe3c.png)

**Comment by redtyyt** [comment]
> ![f4d004c1-c48b-4ffa-b495-1027c918b6f8.png](https://user-images.githubusercontent.com/127892632/236645467-f66295b2-aa62-48cf-b426-37f3f13afe3c.png)

**Comment by Sdatyyt** [comment]
![IMG_20230525_193139_edit_32217596701332.jpg](https://github.com/redtyyt/La-Scuola-Infestata/assets/130348653/a01a2cb0-28d3-4a6c-adbb-83d91986b5a4)

**Comment by Sdatyyt** [comment]
![IMG_20230525_193144_edit_32195153585710.jpg](https://github.com/redtyyt/La-Scuola-Infestata/assets/130348653/ede22112-4b1b-4a40-b4b3-9f11c08420f7)

**Comment by Sdatyyt** [comment]
![IMG_20230525_192720.jpg](https://github.com/redtyyt/La-Scuola-Infestata/assets/130348653/21263138-8585-42c5-bd3a-6079b8b3a3c2)

**Comment by ByLupo345** [comment]
![62f4a887-b915-4398-ad2d-b02c39fae22a.png](https://github.com/redtyyt/La-Scuola-Infestata/assets/127892632/f6161fd1-2266-47c1-891d-75ecc7dfb6eb)

**Comment by ByLupo345** [comment]
- [

**Comment by ByLupo345** [comment]
Questo e' il mio disegno per capodanno

**Comment by ByLupo345** [comment]
139b03ea-dddc-4582-bf6d-002db1d5bc0f.png

**Comment by ByLupo345** [comment]
Boh![ImmGINE](https://github.com/redtyyt/La-Scuola-Infestata/assets/127892632/a74cf42e-d184-443e-8e8a-8ad57181b88d
