### ISSUE TITLE
LA SCUOLA INFESTATA - BACKLOG 

### ISSUE THREAD

**Issue by redtyyt** [redtyyt/La-Scuola-Infestata#6]
`Per tutte le versioni dalla v1P1 alla v3P1`
### Crea una BackLog con tutti i creatori
```
**ATTENZIONE!**
NON UN FILE .MP4, MA UN FILE DI TIPO .JPEG, .JPG, .PNG finquando non troverò un modo per inserire file .MP4
```
> @RonyxDumb

**Comment by RonyxDumb** [comment]
il backlog che sto programmando,  funzionerà con Haxe. quindi per ora, userò file .PNG. Ma nelle cartelle, ti lascierò tutti i file anche in formato .JPEG

**Comment by redtyyt** [comment]
> il backlog che sto programmando,  funzionerà con Haxe. quindi per ora, userò file .PNG. Ma nelle cartelle, ti lascierò tutti i file anche in formato .JPEG

Va bè prova a farlo con HaxeFlixel

**Comment by redtyyt** [comment]
https://github.com/redtyyt/La-Scuola-Infestata/assets/111154398/84001078-0998-4df9-9507-0ad3cf601590

**Comment by RonyxDumb** [comment]
bello il video

**Comment by redtyyt** [comment]
Grazie
